services:
  runner:
    image: runner-image:latest
    restart: always
    environment:
      - REPO=${REPO}
      - PERSONAL_TOKEN=${PERSONAL_TOKEN}
    user: ubuntu
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.75'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    